doc/4-pyspark.md
Adding more examples to showcase reading & writing dataframes.
The input & output URI can be specified at the time of reading / writing dataframe instead of starting pyspark
=> More examples for reading & writing dataframe

src/main/scala/com/mongodb/spark/rdd/MongoRDD.scala, src/main/scala/com/mongodb/spark/rdd/partitioner/MongoSamplePartitioner.scala
This is the same fix as in [7b628edcbbdb9affca11ea7df810085ff987cd7e](https://github.com/mongodb/mongo-spark/commit/7b628edcbbdb9affca11ea7df810085ff987cd7e) to fix [SPARK-81]( https://jira.mongodb.org/browse/SPARK-81).
This has not yet been fixed for Spark versions < 2.0
=> SPARK-81 Set allow disk use to true for all aggregations

doc/1-sparkSQL.md
Some tables  in docs are broken due to empty cells. Fix those by adding &nbsp; in those empty cells.
=> Fix a bug with broken tables in Github

project/scalastyle-config.xml, src/main/scala/com/mongodb/spark/MongoSpark.scala
PR for SPARK-324: MongoSpark SAVE API which accepts MongoConnector instance as argument
- Added a new save method in MongoSpark.scala which also accepts MongoConnector instance.
- Increased maxMethods count to 35 since MongoSpark now has over 30 methods.
=> SPARK-324 - MongoSpark SAVE API which accepts MongoConnector instance as argument

src/integrationTest/java/com/mongodb/spark/sql/connector/read/MongoSparkConnectorReadTest.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoScanBuilder.java
It now handles error cases better by not throwing an exception. It now
will leave the Filter for Spark to handle.
Now handles nested lookups and pushes them down to the aggregation
framework.
SPARK-359
=> Updated MongoScanBuilder

src/main/java/com/mongodb/spark/sql/connector/schema/InferSchema.java, src/test/java/com/mongodb/spark/sql/connector/schema/InferSchemaTest.java, src/test/java/com/mongodb/spark/sql/connector/schema/SchemaTest.java
Ensures that empty arrays, don't force the loss of other documents array types when inferring the schema.
SPARK-375
=> InferSchema empty Array handling

src/integrationTest/java/com/mongodb/spark/sql/connector/read/MongoBatchTest.java, src/main/java/com/mongodb/spark/sql/connector/config/ReadConfig.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoBatch.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoContinuousStream.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoInputPartition.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoInputPartitionHelper.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoMicroBatchStream.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoScanBuilder.java, src/main/java/com/mongodb/spark/sql/connector/read/partitioner/PartitionerHelper.java, src/main/java/com/mongodb/spark/sql/connector/read/partitioner/SamplePartitioner.java, src/test/java/com/mongodb/spark/sql/connector/read/MongoInputPartitionHelperTest.java
Adds a $project stage for all schema fields
~Adds an $exists check for all non-nullable fields~
~Added `include.schema.filters.and.projections` config to allow the feature to be disabled.~
Note: This feature is automatically enabled.
SPARK-376
=> Added automatic schema based filter & projections

src/integrationTest/java/com/mongodb/spark/sql/connector/read/MongoBatchTest.java, src/main/java/com/mongodb/spark/sql/connector/config/ReadConfig.java, src/main/java/com/mongodb/spark/sql/connector/config/WriteConfig.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoBatch.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoContinuousStream.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoMicroBatchStream.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoScanBuilder.java, src/main/java/com/mongodb/spark/sql/connector/schema/BsonDocumentToRowConverter.java, src/main/java/com/mongodb/spark/sql/connector/schema/ConverterHelper.java, src/main/java/com/mongodb/spark/sql/connector/schema/RowToBsonDocumentConverter.java, src/main/java/com/mongodb/spark/sql/connector/write/MongoDataWriter.java, src/test/java/com/mongodb/spark/sql/connector/schema/BsonDocumentToRowConverterTest.java, src/test/java/com/mongodb/spark/sql/connector/schema/InferSchemaTest.java, src/test/java/com/mongodb/spark/sql/connector/schema/RowToBsonDocumentConverterTest.java, src/test/java/com/mongodb/spark/sql/connector/schema/SchemaTest.java
Added two new configurations:
`spark.mongodb.read.outputExtendedJson=false`
`spark.mongodb.write.convertJson=false`
SPARK-311
=> Support extended json

src/integrationTest/java/com/mongodb/spark/sql/connector/read/MongoBatchTest.java, src/integrationTest/java/com/mongodb/spark/sql/connector/write/MongoSparkConnectorWriteTest.java, src/main/java/com/mongodb/spark/sql/connector/schema/RowToBsonDocumentConverter.java, src/test/java/com/mongodb/spark/sql/connector/schema/RowToBsonDocumentConverterTest.java, src/test/java/com/mongodb/spark/sql/connector/schema/SchemaTest.java
Fixes issue saving arrays / maps containing nulls
Top level fields containing null are included when writing the document. This mirrors nulls and creating of rows.
Users should filter data containing nulls, should they not want to save that data.
SPARK-384
SPARK-351
=> Ensure null values can be converted to BsonNull

src/integrationTest/java/com/mongodb/spark/sql/connector/read/MongoBatchTest.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoInputPartitionHelper.java, src/main/java/com/mongodb/spark/sql/connector/read/partitioner/PaginateBySizePartitioner.java, src/main/java/com/mongodb/spark/sql/connector/read/partitioner/SamplePartitioner.java
Tests against timeseries where there is no count.
SPARK-387
=> Ensure partitioners can handle lack of count in storagestats

src/integrationTest/java/com/mongodb/spark/sql/connector/read/MongoBatchTest.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoScanBuilder.java
Spark automatically escapes some field names
eg ones containing a hyphen. Check and unescape any escaped field names before applying the filter
to MongoDB.
SPARK-393
=> Support escaped fieldnames in filters

src/integrationTest/java/com/mongodb/spark/sql/connector/read/MongoBatchTest.java, src/main/java/com/mongodb/spark/sql/connector/config/WriteConfig.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoScanBuilder.java, src/main/java/com/mongodb/spark/sql/connector/schema/RowToBsonDocumentConverter.java, src/main/java/com/mongodb/spark/sql/connector/write/MongoDataWriter.java, src/test/java/com/mongodb/spark/sql/connector/schema/RowToBsonDocumentConverterTest.java, src/test/java/com/mongodb/spark/sql/connector/schema/SchemaTest.java
Added new config: `convertJson.nestedValuesOnly`
Which will only attempt to convert strings that contain nested Json Objects or Arrays.
Useful when dealing with extended Json and ensures strings that contain json like values are not automatically converted.
Example:
```
convertJson=true
convertJson.nestedValuesOnly=false
"{a: 1}"    => {a: 1}
"[1, 2, 3]" => [1, 2, 3]
"true"      => true
"0122345"   => 12345
"{a:b:c}"   => "{a:b:c}"
convertJson=true
convertJson.nestedValuesOnly=true
"{a: 1}"    => {a: 1}
"[1, 2, 3]" => [1, 2, 3]
"true"      => "true"
"0122345"   => "012345"
"{a:b:c}"   => "{a:b:c}"
```
SPARK-388 SPARK-405
=> Json string conversion improvements

src/integrationTest/java/com/mongodb/spark/sql/connector/read/MongoBatchTest.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoScanBuilder.java
~[$ne](https://www.mongodb.com/docs/manual/reference/operator/query/ne/#mongodb-query-op.-ne) also excludes documents where the field doesn't exist (this used to not be the case).~
SPARK-410
=> Use $ne for isNotNull

src/main/java/com/mongodb/spark/sql/connector/read/MongoMicroBatchPartitionReader.java
=> Stop calling `MongoMicroBatchPartitionReader.tryNext` if the resume token timestamp is equal to the end offset timestamp

src/integrationTest/java/com/mongodb/spark/sql/connector/mongodb/MongoSparkConnectorTestCase.java, src/integrationTest/java/com/mongodb/spark/sql/connector/read/AbstractMongoStreamTest.java, src/integrationTest/java/com/mongodb/spark/sql/connector/schema/InferSchemaIntegrationTest.java, src/main/java/com/mongodb/spark/sql/connector/MongoTable.java, src/main/java/com/mongodb/spark/sql/connector/config/AbstractMongoConfig.java, src/main/java/com/mongodb/spark/sql/connector/config/CollectionsConfig.java, src/main/java/com/mongodb/spark/sql/connector/config/MongoConfig.java, src/main/java/com/mongodb/spark/sql/connector/config/ReadConfig.java, src/main/java/com/mongodb/spark/sql/connector/config/WriteConfig.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoContinuousPartitionReader.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoInputPartitionHelper.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoMicroBatchPartitionReader.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoScan.java, src/main/java/com/mongodb/spark/sql/connector/read/partitioner/PartitionerHelper.java, src/main/java/com/mongodb/spark/sql/connector/schema/InferSchema.java, src/test/java/com/mongodb/spark/sql/connector/config/CollectionsConfigTest.java, src/test/java/com/mongodb/spark/sql/connector/config/MongoConfigTest.java, src/test/java/com/mongodb/spark/sql/connector/read/MongoScanTest.java
For the description of the new functionality and configuration see the API documentation of the following program elements:
- `MongoConfig.COLLECTION_NAME_CONFIG`
- `CollectionsConfig.Type` and its values.
For the complete picture, please see also [this](https://jira.mongodb.org/browse/SPARK-404?focusedCommentId=6018950&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-6018950) comment.
Note that I marked all the new `public` program elements as `@ApiStatus.Internal`. I am not sure whether that is correct, but I don't see myself why they need to be part of the API, nor do I see why all the existing program elements that allow accessing the configuration for reading had to be made part of the API previously.
SPARK-404
=> Support scanning from multiple collections

src/integrationTest/java/com/mongodb/spark/sql/connector/read/MongoBatchTest.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoScanBuilder.java, src/main/java/com/mongodb/spark/sql/connector/schema/RowToBsonDocumentConverter.java, src/test/java/com/mongodb/spark/sql/connector/schema/RowToBsonDocumentConverterTest.java
Improves performance as its only done once rather than per row.
Returns performance to the 3.x branch as that also memoizes the data type to bson value mapping function for each field.
SPARK-419
=> Cache the DataType to BsonValue mapping

src/main/java/com/mongodb/spark/sql/connector/connection/DefaultMongoClientFactory.java, src/main/java/com/mongodb/spark/sql/connector/connection/MongoClientCache.java, src/test/java/com/mongodb/spark/sql/connector/connection/DefaultMongoClientFactoryTest.java, src/test/java/com/mongodb/spark/sql/connector/connection/MongoClientCacheTest.java
MongoDriverInformation does not implement hashCode/equals which effectively prevents DefaultMongoClientFactory from being used as a key in MongoClientCache i.e. even for the same configuration factories are never equal and create multiple, redundant cache entries.
=> Fix MongoClientCache for factories with same/equal configurations

src/main/java/com/mongodb/spark/sql/connector/schema/RowToBsonDocumentConverter.java, src/test/java/com/mongodb/spark/sql/connector/schema/SchemaTest.java
=> Fix handling of empty strings when parsing

src/main/java/com/mongodb/spark/sql/connector/config/WriteConfig.java, src/test/java/com/mongodb/spark/sql/connector/config/MongoConfigTest.java
=> Fix convertJson configuration parsing

src/main/java/com/mongodb/spark/sql/connector/config/ReadConfig.java, src/main/java/com/mongodb/spark/sql/connector/schema/InferSchema.java, src/test/java/com/mongodb/spark/sql/connector/config/MongoConfigTest.java, src/test/java/com/mongodb/spark/sql/connector/schema/InferSchemaTest.java
Added a new configuration: `schemaHints`.
Users can now supply schema to enforce the schema information about known field types when inferring schema.
Supports the following Spark formats:
- DDL: `value STRING,count INT`
- SQL DDL: `STRUCT<value: STRING, count: INT>`
- Simple String DDL: `struct<value:string,count:int>`
- JSON: ```{"type":"struct","fields":[ {"name":"value","type":"string","nullable":true}, {"name":"count","type":"integer","nullable":true}]}```
To create DDL or Json schema strings simply use the Spark shell:
```
import org.apache.spark.sql.types._
val mySchema = StructType(Seq(StructField("value", StringType), StructField("count", IntegerType)))
mySchema.toDDL
mySchema.sql
mySchema.simpleString
mySchema.json
```
Or in PySpark:
```
from pyspark.sql.types import StructType, …
```
=> Added Schema hints for use when inferring schemas.

src/integrationTest/java/com/mongodb/spark/sql/connector/mongodb/MongoSparkConnectorHelper.java, src/integrationTest/java/com/mongodb/spark/sql/connector/mongodb/MongoSparkConnectorTestCase.java, src/integrationTest/java/com/mongodb/spark/sql/connector/read/partitioner/AutoBucketPartitionerTest.java, src/main/java/com/mongodb/spark/sql/connector/assertions/Assertions.java, src/main/java/com/mongodb/spark/sql/connector/read/partitioner/AutoBucketPartitioner.java, src/test/java/com/mongodb/spark/sql/connector/read/partitioner/AutoBucketPartitionerUnitTest.java
A `$sample` based partitioner that provides support for all collection types. Supports partitioning across single or multiple fields, including nested fields.
The logic for the partitioner is as follows:
- Calculate the number of documents per partition. Runs a `$collStats` aggregation to get the average document size.
- Determines the total count of documents. Uses the `$collStats` count or by running a `countDocuments` query if the user supplies their own `aggregation.pipeline` configuration.
- Determines the number of partitions. Calculated as: `count / number of documents per partition`
- Determines the number of documents to $sample. Calculated as: `samples per partition * number of partitions`.
- Creates the aggregation pipeline to generate the partitions. 
```
[{$match: <the $match …
```
=> Auto Bucket Partitioner

build.gradle.kts, src/integrationTest/java/com/mongodb/spark/sql/connector/read/AbstractMongoStreamTest.java, src/integrationTest/java/com/mongodb/spark/sql/connector/read/MongoBatchTest.java, src/main/java/com/mongodb/spark/sql/connector/config/ReadConfig.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoBatch.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoBatchPartitionReader.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoContinuousPartitionReader.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoContinuousStream.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoMicroBatchPartitionReader.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoMicroBatchStream.java, src/main/java/com/mongodb/spark/sql/connector/schema/BsonDocumentToRowConverter.java, src/main/java/com/mongodb/spark/sql/connector/schema/ConverterHelper.java, src/main/java/com/mongodb/spark/sql/connector/schema/InferSchema.java, src/main/java_scala_212/com/mongodb/spark/sql/connector/interop/JavaScala.java, src/main/java_scala_213/com/mongodb/spark/sql/connector/interop/JavaScala.java, src/test/java/com/mongodb/spark/sql/connector/config/MongoConfigTest.java, src/test/java/com/mongodb/spark/sql/connector/schema/BsonDocumentToRowConverterTest.java, src/test/java/com/mongodb/spark/sql/connector/schema/InferSchemaTest.java
Adds the `mode` configuration allowing for different parsing strategies when handling documents that don't match the expected schema during reads.
The options are:
- `FAILFAST` (default) throw an exception when parsing a document that doesn't match the schema.
- `PERMISSIVE` Sets any invalid fields to `null`. Combine with the `columnNameOfCorruptRecord` configuration if you want to store any invalid documents as an extended json string.
- `DROPMALFORMED` ignores the whole document.
Adds the `columnNameOfCorruptRecord` configuration whic extends the `PERMISSIVE` mode. When configured it saves the whole invalid document as extended json in that column, as long as its defined in the Schema. Inferred schemas will add the `columnNameOfCorruptRecord` column if set and the `mode` is …
=> Added parse mode support when reading data from MongoDB.

src/integrationTest/java/com/mongodb/spark/sql/connector/mongodb/MongoSparkConnectorTestCase.java, src/integrationTest/java/com/mongodb/spark/sql/connector/utils/SparkHadoopUtilsTest.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoContinuousStream.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoMicroBatchStream.java, src/main/java/com/mongodb/spark/sql/connector/read/MongoOffsetStore.java, src/main/java/com/mongodb/spark/sql/connector/utils/SparkHadoopUtils.java, src/main/java/com/mongodb/spark/sql/connector/utils/package-info.java
Spark expects hadoop configurations to be prefixed with `spark.hadoop`. However, documentation on the web omits this prefix when setting filesystem configuration - See the azure storage docs.
The issue the connector has is the `MongoOffset` support just uses the `SparkContext.hadoopConfiguration()` helper method, which omits any non-prefixed configuration. So this improvement adds any filesystem configuration prefixed with `fs.` to the hadoop configuration. This ensures that the `MongoOffset`s use of the Hadoop filesystem includes the configuraion.
SPARK-438
=> Improved support for MongoOffsets using hadoop file systems

src/main/java/com/mongodb/spark/sql/connector/connection/DefaultMongoClientFactory.java, src/test/java/com/mongodb/spark/sql/connector/connection/MongoClientCacheTest.java
Spark pushes down aggregation pipelines in the configuration when acquiring MongoClient instances. This change modifies the MongoClientFactory to only take the connection into account for lookups in MongoClientCache.
Without this change different queries against the same MongoDB database result in multiple MongoClient instances preventing caching in those scenarios.
SPARK-441
=> Allow reuse of MongoClient instances for the same collection

src/test/java/com/mongodb/spark/sql/connector/connection/MongoClientCacheTest.java
* `factoriesWithEqualSimpleConfigsCreateSameClientsThroughCache` can be now enabled since the [referenced PR](https://github.com/mongodb/mongo-spark/pull/112) has been merged, without that fix it would fail
* `factoriesWithSameSimpleConfigCreateSameClientsThroughCache` can be removed as it is identical to `factoriesWithSameConfigCreateSameClientsThroughCache`
=> Update tests in MongoClientCacheTest

src/integrationTest/java/com/mongodb/spark/sql/connector/mongodb/MongoSparkConnectorTestCase.java, src/integrationTest/java/com/mongodb/spark/sql/connector/read/partitioner/AutoBucketPartitionerTest.java, src/main/java/com/mongodb/spark/sql/connector/config/ReadConfig.java, src/main/java/com/mongodb/spark/sql/connector/read/partitioner/AutoBucketPartitioner.java
It uses the $bucketAuto aggregation stage and works for compound keys as well as single keys.
SPARK-444
=> Updated the default partitioner to the AutoBucketPartitioner
